env:
  browser: true
  es2022: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
globals:
  Turbo: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
