# fly.toml app configuration file generated for smooth-pdf on 2023-11-23T14:36:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smooth-pdf"
primary_region = "iad"

[env]
  HOSTNAME = "smooth.fly.dev"
  PORT = 3000
  TIMEOUT = 15
  FORMAT = "letter"
  JAVASCRIPT = "false"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
