---
regions:
  iad:
    name: Ashburn, Virginia (US)
    lat: 39.02214
    lon: -77.462555
  ord:
    name: Chicago, Illinois (US)
    lat: 41.891544
    lon: -87.63039
  dfw:
    name: Dallas, Texas (US)
    lat: 32.778286
    lon: -96.7984
  mia:
    name: Miami, Florida (US)
    lat: 25.7877
    lon: -80.2241
  sjc:
    name: San Jose, California (US)
    lat: 37.3516
    lon: -121.89674
  sea:
    name: Seattle, Washington (US)
    lat: 47.6097
    lon: -122.3331
  syd:
    name: Sydney, Australia
    lat: -33.86603
    lon: 151.20692
studios:
  alexandria:
    lat: 38.805
    lon: -77.043
  annapolis:
    lat: 38.977
    lon: -76.49
  austin:
    lat: 30.268
    lon: -97.743
  carmel:
    lat: 39.978
    lon: -86.126
  cary:
    lat: 35.79
    lon: -78.781
  charlotte:
    lat: 35.223
    lon: -80.838
  chicago:
    lat: 41.884
    lon: -87.632
  clearwater:
    lat: 27.966
    lon: -82.796
  dayton:
    lat: 39.759
    lon: -84.194
  durham:
    lat: 35.995
    lon: -78.897
  glenview:
    lat: 42.078
    lon: -87.799
  greenhills:
    lat: 36.105
    lon: -86.815
  harrisburg:
    lat: 40.26
    lon: -76.882
  kennesaw:
    lat: 34.023
    lon: -84.616
  lakeview:
    lat: 42.254
    lon: -88.001
  livermore:
    lat: 37.676
    lon: -121.759
  montreal:
    lat: 45.5019
    lon: -73.5674
  raleigh:
    lat: 35.785
    lon: -78.643
  richmond:
    lat: 37.541
    lon: -77.434
  roanoke:
    lat: 37.272
    lon: -79.941
  salem:
    lat: 44.933
    lon: -123.04
  sarasota:
    lat: 27.339
    lon: -82.539
  slc:
    lat: 40.7608
    lon: -111.891
  sugarland:
    lat: 29.633
    lon: -95.601
  sydney:
    lat: -33.8302783
    lon: 151.1570269
  vabeach:
    lat: 36.755
    lon: -76.06
  woodlands:
    lat: 30.158
    lon: -95.456
