---
2022:                                                                           
  annapolis:
    :name: Annapolis
    :events:                                          
      :medalball:                                     
        :name: Metal Ball                             
      :chesapeakeclassic:
        :name: Chesapeake Classic
      :gratitudegala:
        :name: Gratitude Gala
  charlotte:
    :name: Charlotte
  harrisburg:                                                                   
    :name: Harrisburg
  vabeach:                                                                   
    :name: Virginia Beach
