---
2023:                                                                           
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      :medalball:
        :name: Metal Ball
      :chesapeakeclassic:
        :name: Chesapeake Classic
      :gratitudegala:
        :name: Gratitude Gala
  charlotte:
    :name: Charlotte
    :region: iad
    :logo: arthur-murray-logo.gif
  harrisburg:                                                                   
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  raleigh:
    :name: Raleigh
    :region: iad
    :logo: arthur-murray-logo.gif
2022:                                                                           
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:                                          
      :medalball:                                     
        :name: Metal Ball                             
      :chesapeakeclassic:
        :name: Chesapeake Classic
      :gratitudegala:
        :name: Gratitude Gala
  cary:
    :name: Cary
    :region: iad
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: iad
    :logo: arthur-murray-logo.gif
  harrisburg:                                                                   
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:                                                                   
    :name: Kennesaw
    :region: iad
    :logo: arthur-murray-logo.gif
  vabeach:                                                                   
    :name: Virginia Beach
    :region: iad
    :logo: arthur-murray-logo.gif
