---
2023:                                                                           
  alexandria:
    :name: Alexandria
    :region: iad
    :logo: arthur-murray-logo.gif
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      :medalball:
        :name: Metal Ball
      :chesapeakeclassic:
        :name: Chesapeake Classic
      :gratitudegala:
        :name: Gratitude Gala
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: arthur-murray-logo.gif
  chicago:
    :name: Chicago
    :region: ord
    :logo: arthur-murray-logo.gif
  clearwater:
    :name: Clearwater
    :region: mia
    :logo: arthur-murray-logo.gif
    :events:
      :glassslipper:
        :name: Glass Slipper Gala
      :nationaldance:
        :name: National Dance Day
      :snowball:
        :name: Snowball
      :flamingoopener:
        :name: Flamingo Opener
  durham:
    :name: Durham
    :region: iad
    :logo: arthur-murray-logo.gif
  glenview:
    :name: Glenview
    :region: ord
    :logo: arthur-murray-logo.gif
  harrisburg:                                                                   
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  lakeview:
    :name: Lakeview
    :region: ord
    :logo: arthur-murray-logo.gif
  raleigh:
    :name: Raleigh
    :region: iad
    :logo: arthur-murray-logo.gif
  richmond:
    :name: Richmond
    :region: iad
    :logo: arthur-murray-logo.gif
  sugarland:
    :name: Sugar Land
    :region: dfw
    :logo: arthur-murray-logo.gif
  vabeach:                                                                   
    :name: Virginia Beach
    :region: iad
    :logo: arthur-murray-logo.gif
  woodlands:
    :name: Woodlands
    :region: dfw
    :logo: arthur-murray-logo.gif
2022:                                                                           
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:                                          
      :medalball:                                     
        :name: Metal Ball                             
      :chesapeakeclassic:
        :name: Chesapeake Classic
      :gratitudegala:
        :name: Gratitude Gala
  cary:
    :name: Cary
    :region: iad
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: arthur-murray-logo.gif
  harrisburg:                                                                   
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:                                                                   
    :name: Kennesaw
    :region: atl
    :logo: arthur-murray-logo.gif
  vabeach:                                                                   
    :name: Virginia Beach
    :region: iad
    :logo: arthur-murray-logo.gif
