---
2025:
  bellevue:
    :name: Bellevue
    :region: sea
    :logo: ''
    :events:
      hawaii:
        :name: Hawaii
      winter:
        :name: Winter
      summer-medal-ball:
        :name: Summer Medal Ball
      summer-showcase:
        :name: Summer Showcase
  boston:
    :name: Boston
    :region: bos
    :logo: ''
    :events:
      april:
        :name: April
      mini-comp:
        :name: Mini Comp
      october:
        :name: October
  livermore:
    :name: Livermore
    :region: sjc
    :logo: arthur-murray-logo.gif
    :events:
      the-music-of-prince:
        :name: The Music of Prince
      james-bond:
        :name: James Bond
  raleigh:
    :name: Raleigh
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      disney:
        :name: Disney
      in-house:
        :name: In House
2024:
  adelaide:
    :name: Adelaide
    :region: syd
    :logo: arthur-murray-logo.gif
    :events:
      starry-night:
        :name: Starry Night
      rewind:
        :name: Rewind
      northside:
        :name: Northside
      adalaide:
        :name: Adalaide
  alexandria:
    :name: Alexandria
    :region: iad
    :logo: arthur-murray-logo.gif
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  austin:
    :name: Austin
    :region: dfw
    :logo: arthur-murray-logo.gif
  bellevue:
    :name: Bellevue
    :region: sea
    :logo: ''
    :events:
      june-medal-ball:
        :name: June Medal Ball
      august-showcase:
        :name: August Showcase
      october-mini-comp:
        :name: October Mini Comp
      spotlight-ball:
        :name: Spotlight ball
      december-medal-ball:
        :name: December Medal Ball
  boston:
    :name: Boston
    :region: bos
    :logo: ''
  carmel:
    :name: Carmel
    :region: ord
    :logo: arthur-murray-logo.gif
    :events:
      spring-showcase:
        :name: Spring Showcase
      back-to-the-80s:
        :name: Back to the 80’s
  cary:
    :name: Cary
    :region: iad
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: ''
  chicago:
    :name: Chicago
    :region: ord
    :logo: arthur-murray-logo.gif
  clearwater:
    :name: Clearwater
    :region: mia
    :logo: arthur-murray-logo.gif
    :events:
      texas-opener:
        :name: Texas Opener
      birthday-bash:
        :name: Birthday Bash
      glass-slipper:
        :name: Glass Slipper Gala
      northstar-opener:
        :name: Northstar Opener
      flamingo-opener:
        :name: Flamingo Opener
      fright-fest:
        :name: Fright Fest
      snowball:
        :name: Snowball
  cranford:
    :name: Cranford
    :region: ewr
    :logo: arthur-murray-logo.gif
    :events:
      spring-freestyles:
        :name: Spring Freestyles
      fall-freestyles:
        :name: Fall Freestyles
  dayton:
    :name: Dayton
    :region: ord
    :logo: arthur-murray-logo.gif
  durham:
    :name: Durham
    :region: iad
    :logo: arthur-murray-logo.gif
  everett:
    :name: everett
    :region: sea
    :logo: ''
  glenview:
    :name: Glenview
    :region: ord
    :logo: arthur-murray-logo.gif
    :events:
      chicagoland-feb:
        :name: Chicagoland Feb
      chicagoland-sept:
        :name: Chicagoland Sept
  greenhills:
    :name: Nashville-Green Hills
    :region: atl
    :logo: arthur-murray-logo.gif
    :events:
      spring:
        :name: Spring
      music-city:
        :name: Music City
  harrisburg:
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:
    :name: Kennesaw
    :region: atl
    :logo: arthur-murray-logo.gif
  lakeview:
    :name: Lakeview
    :region: ord
    :logo: arthur-murray-logo.gif
    :events:
      showcase-rounds:
        :name: Showcase Rounds
      graduation-nights:
        :name: Graduation Nights
      in-studio:
        :name: In Studio
      showcase-rounds-september:
        :name: Showcase Rounds - September
      graduation-nights-2:
        :name: Graduation Nights 2
  laval:
    :name: Laval
    :region: bos
    :logo: arthur-murray-logo.gif
  lincolnshire:
    :name: Lincolnshire
    :region: ord
    :logo: arthur-murray-logo.gif
  livermore:
    :name: Livermore
    :region: sjc
    :logo: arthur-murray-logo.gif
    :events:
      pep-rally:
        :name: Pep Rally
      district-showcase:
        :name: District Showcase
      barbecue-pep-rally:
        :name: Barbecue Pep Rally
      live-medal-ball:
        :name: Live Medal Ball
      willie-wonkas-magical-night:
        :name: Willie Wonka’s Magical Night
      extravaganza:
        :name: Extravaganza
  lwr:
    :name: Lakewood Ranch
    :region: mia
    :logo: ''
  manchester:
    :name: Manchester
    :region: bos
    :logo: ''
  mdballroom:
    :name: Memorial DanceSport Ballroom
    :region: dfw
    :logo: mdballroom.webp
    :events:
      february-team-match:
        :name: February Team Match
      june-team-match:
        :name: June Team Match
  merrillville:
    :name: Merrillville
    :region: ord
    :logo: arthur-murray-logo.gif
    :events:
      medal-ball:
        :name: Medal Ball
      team-match:
        :name: Team Match
      graduation-night:
        :name: Graduation Night
      newsome-twosome:
        :name: Newsome Twosome
      snowball-spotlight:
        :name: Snowball Spotlight
  monterey:
    :name: Monterey
    :region: sjc
    :logo: ''
  montgomery:
    :name: Montgomery
    :region: ord
    :logo: ''
    :events:
      dreamland:
        :name: Dreamland
      fort-wayne:
        :name: Fort Wayne
      cddc:
        :name: CDDC
      swing-sway:
        :name: Swing & Sway
  montreal:
    :name: Montreal
    :region: bos
    :logo: arthur-murray-logo.gif
    :events:
      june:
        :name: June
      november:
        :name: November
  perth:
    :name: Perth
    :region: syd
    :logo: arthur-murray-logo.gif
    :events:
      karaoke:
        :name: Karaoke
      country:
        :name: Country
      pin-up-50s:
        :name: Pin Up 50's
      hawaiian:
        :name: Hawaiian
      christmas:
        :name: Christmas
  petaluma:
    :name: Petaluma
    :region: sjc
    :logo: arthur-murray-logo.gif
  raleigh:
    :name: Raleigh
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      casino-royale:
        :name: Casino Royale
      in-house:
        :name: In House
  richmond:
    :name: Richmond
    :region: atl
    :logo: arthur-murray-logo.gif
    :events:
      medal-ball:
        :name: Medal Ball
      team-match:
        :name: Team Match
      nouveau-duo:
        :name: Nouveau Duo
  ridgewood:
    :name: Ridgewood
    :region: ewr
    :logo: arthur-murray-logo.gif
  roanoke:
    :name: Roanoke
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      team-match:
        :name: Team Match
      spring-showcase:
        :name: Spring Showcase
      medal-ball:
        :name: Medal Ball
      fall-showcase:
        :name: Fall Showcase
  salem:
    :name: Salem
    :region: sea
    :logo: arthur-murray-logo.gif
    :events:
      spring:
        :name: Spring
      fall:
        :name: Fall
  sanjose:
    :name: San Jose
    :region: sjc
    :logo: arthur-murray-logo.gif
    :events:
      march:
        :name: March
      september:
        :name: September
  sarasota:
    :name: Sarasota
    :region: mia
    :logo: arthur-murray-logo.gif
  schaumburg:
    :name: Schaumburg
    :region: ord
    :logo: arthur-murray-logo.gif
  slc:
    :name: Salt Lake City
    :region: sjc
    :logo: arthur-murray-logo.gif
    :events:
      june:
        :name: June
      medal-ball:
        :name: Medal Ball
  stockton:
    :name: Stockton
    :region: sjc
    :logo: ''
    :events:
      walk-this-way:
        :name: Walk This Way
      dance-down-memory-lane:
        :name: Dance Down Memory Lane
  sugarland:
    :name: Sugar Land
    :region: dfw
    :logo: arthur-murray-logo.gif
  sydney:
    :name: Sydney
    :region: syd
    :logo: arthur-murray-logo.gif
    :events:
      gatsby:
        :name: Gatsby
      dancing-with-the-stars:
        :name: Dancing With The Stars
  vabeach:
    :name: Virginia Beach
    :region: iad
    :logo: ''
    :events:
      newsome-twosome:
        :name: Medal Ball - Newsome Twosome
      summer-beach-bash:
        :name: Summer Beach Bash
      freestyles:
        :name: Virginia Beach Freestyles
  vicenza:
    :name: Vicenza
    :region: waw
    :logo: ''
  warsaw:
    :name: Warsaw
    :region: waw
    :logo: arthur-murray-logo.gif
    :events:
      june-warsaw-freestyle:
        :name: June Warsaw Freestyle
      july-kiev:
        :name: July Kiev
      freestyle-showcase-warsaw-2024:
        :name: Freestyle Showcase Warsaw 2024
      freestyle-showcase-kyiv-2024:
        :name: Freestyle Showcase Kyiv 2024
  westchester:
    :name: West Chester
    :region: ord
    :logo: arthur-murray-logo.gif
  woodlands:
    :name: Woodlands
    :region: dfw
    :logo: arthur-murray-logo.gif
2023:
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  carmel:
    :name: Carmel
    :region: ord
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: ''
  chicago:
    :name: Chicago
    :region: ord
    :logo: arthur-murray-logo.gif
  clearwater:
    :name: Clearwater
    :region: mia
    :logo: arthur-murray-logo.gif
    :events:
      glassslipper:
        :name: Glass Slipper Gala
      nationaldance:
        :name: National Dance Day
      flamingoopener:
        :name: Flamingo Opener
      flamingo-fright:
        :name: Flamingo Fright Festival
      snowball:
        :name: Snowball
  durham:
    :name: Durham
    :region: iad
    :logo: arthur-murray-logo.gif
  greenhills:
    :name: Nashville-Green Hills
    :region: atl
    :logo: arthur-murray-logo.gif
  harrisburg:
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:
    :name: Kennesaw
    :region: atl
    :logo: arthur-murray-logo.gif
  lakeview:
    :name: Lakeview
    :region: ord
    :logo: arthur-murray-logo.gif
    :events:
      showcase:
        :name: Showcase
      showcase-rounds:
        :name: Showcase Rounds
  livermore:
    :name: Livermore
    :region: sjc
    :logo: arthur-murray-logo.gif
  montreal:
    :name: Montreal
    :region: bos
    :logo: arthur-murray-logo.gif
  raleigh:
    :name: Raleigh
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      night-in-paris:
        :name: A Night In Paris
      team-match:
        :name: Team Match
  richmond:
    :name: Richmond
    :region: atl
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Medal Ball
      teammatch:
        :name: Team Match
      nouveau-duo:
        :name: Nouveau Duo
  salem:
    :name: Salem
    :region: sea
    :logo: arthur-murray-logo.gif
  sarasota:
    :name: Sarasota
    :region: mia
    :logo: arthur-murray-logo.gif
  sugarland:
    :name: Sugar Land
    :region: dfw
    :logo: arthur-murray-logo.gif
  sydney:
    :name: Sydney
    :region: syd
    :logo: arthur-murray-logo.gif
  vabeach:
    :name: Virginia Beach
    :region: iad
    :logo: ''
  woodlands:
    :name: Woodlands
    :region: dfw
    :logo: arthur-murray-logo.gif
2022:
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  cary:
    :name: Cary
    :region: iad
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: ''
  harrisburg:
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:
    :name: Kennesaw
    :region: atl
    :logo: arthur-murray-logo.gif
  vabeach:
    :name: Virginia Beach
    :region: iad
    :logo: ''
