---
2024:
  adelaide:
    :name: Adelaide
    :region: syd
    :logo: arthur-murray-logo.gif
  alexandria:
    :name: Alexandria
    :region: iad
    :logo: arthur-murray-logo.gif
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  austin:
    :name: Austin
    :region: dfw
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: arthur-murray-logo.gif
  chicago:
    :name: Chicago
    :region: ord
    :logo: arthur-murray-logo.gif
  clearwater:
    :name: Clearwater
    :region: mia
    :logo: arthur-murray-logo.gif
    :events:
      texas-opener:
        :name: Texas Opener
      birthday-bash:
        :name: Birthday Bash
      glass-slipper:
        :name: Glass Slipper Gala
      northstar-opener:
        :name: Northstar Opener
      flamingo-opener:
        :name: Flamingo Opener
      fright-fest:
        :name: Fright Fest
      snowball:
        :name: Snowball
  cranford:
    :name: Cranford
    :region: ewr
    :logo: arthur-murray-logo.gif
  dayton:
    :name: Dayton
    :region: ord
    :logo: arthur-murray-logo.gif
  glenview:
    :name: Glenview
    :region: ord
    :logo: arthur-murray-logo.gif
  harrisburg:
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:
    :name: Kennesaw
    :region: atl
    :logo: arthur-murray-logo.gif
  lakeview:
    :name: Lakeview
    :region: ord
    :logo: arthur-murray-logo.gif
  laval:
    :name: Laval
    :region: yul
    :logo: arthur-murray-logo.gif
  lincolnshire:
    :name: Lincolnshire
    :region: ord
    :logo: arthur-murray-logo.gif
  livermore:
    :name: Livermore
    :region: sjc
    :logo: arthur-murray-logo.gif
    :events:
      pep-rally:
        :name: Pep Rally
      district-showcase:
        :name: District Showcase
  mdballroom:
    :name: Memorial DanceSport Ballroom
    :region: dfw
    :logo: mdballroom.webp
  merrillville:
    :name: Merrillville
    :region: ord
    :logo: arthur-murray-logo.gif
    :events:
      medal-ball:
        :name: Medal Ball
      team-match:
        :name: Team Match
      graduation-night:
        :name: Graduation Night
      newsome-twosome:
        :name: Newsome Twosome
      snowball-spotlight:
        :name: Snowball Spotlight
  perth:
    :name: Perth
    :region: syd
    :logo: arthur-murray-logo.gif
  raleigh:
    :name: Raleigh
    :region: iad
    :logo: arthur-murray-logo.gif
  ridgewood:
    :name: Ridgewood
    :region: ewr
    :logo: arthur-murray-logo.gif
  roanoke:
    :name: Roanoke
    :region: iad
    :logo: arthur-murray-logo.gif
  salem:
    :name: Salem
    :region: sea
    :logo: arthur-murray-logo.gif
  sanjose:
    :name: San Jose
    :region: sjc
    :logo: arthur-murray-logo.gif
  schaumburg:
    :name: Schaumburg
    :region: ord
    :logo: arthur-murray-logo.gif
  slc:
    :name: Salt Lake City
    :region: sjc
    :logo: arthur-murray-logo.gif
  vabeach:
    :name: Virginia Beach
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      newsome-twosome:
        :name: Medal Ball - Newsome Twosome
      freestyles:
        :name: Virginia Beach Freestyles
  warsaw:
    :name: Warsaw
    :region: waw
    :logo: arthur-murray-logo.gif
  westchester:
    :name: West Chester
    :region: ord
    :logo: arthur-murray-logo.gif
2023:
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  carmel:
    :name: Carmel
    :region: ord
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: arthur-murray-logo.gif
  chicago:
    :name: Chicago
    :region: ord
    :logo: arthur-murray-logo.gif
  clearwater:
    :name: Clearwater
    :region: mia
    :logo: arthur-murray-logo.gif
    :events:
      glassslipper:
        :name: Glass Slipper Gala
      nationaldance:
        :name: National Dance Day
      flamingoopener:
        :name: Flamingo Opener
      flamingo-fright:
        :name: Flamingo Fright Festival
      snowball:
        :name: Snowball
  durham:
    :name: Durham
    :region: iad
    :logo: arthur-murray-logo.gif
  greenhills:
    :name: Nashville-Green Hills
    :region: atl
    :logo: arthur-murray-logo.gif
  harrisburg:
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:
    :name: Kennesaw
    :region: atl
    :logo: arthur-murray-logo.gif
  lakeview:
    :name: Lakeview
    :region: ord
    :logo: arthur-murray-logo.gif
    :events:
      showcase:
        :name: Showcase
      showcase-rounds:
        :name: Showcase Rounds
  livermore:
    :name: Livermore
    :region: sjc
    :logo: arthur-murray-logo.gif
  montreal:
    :name: Montreal
    :region: yul
    :logo: arthur-murray-logo.gif
  raleigh:
    :name: Raleigh
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      night-in-paris:
        :name: A Night In Paris
      team-match:
        :name: Team Match
  richmond:
    :name: Richmond
    :region: atl
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Medal Ball
      teammatch:
        :name: Team Match
      nouveau-duo:
        :name: Nouveau Duo
  salem:
    :name: Salem
    :region: sea
    :logo: arthur-murray-logo.gif
  sarasota:
    :name: Sarasota
    :region: mia
    :logo: arthur-murray-logo.gif
  sugarland:
    :name: Sugar Land
    :region: dfw
    :logo: arthur-murray-logo.gif
  sydney:
    :name: Sydney
    :region: syd
    :logo: arthur-murray-logo.gif
  vabeach:
    :name: Virginia Beach
    :region: iad
    :logo: arthur-murray-logo.gif
  woodlands:
    :name: Woodlands
    :region: dfw
    :logo: arthur-murray-logo.gif
2022:
  annapolis:
    :name: Annapolis
    :region: iad
    :logo: arthur-murray-logo.gif
    :events:
      medalball:
        :name: Metal Ball
      chesapeakeclassic:
        :name: Chesapeake Classic
      gratitudegala:
        :name: Gratitude Gala
  cary:
    :name: Cary
    :region: iad
    :logo: arthur-murray-logo.gif
  charlotte:
    :name: Charlotte
    :region: atl
    :logo: arthur-murray-logo.gif
  harrisburg:
    :name: Harrisburg
    :region: iad
    :logo: arthur-murray-logo.gif
  kennesaw:
    :name: Kennesaw
    :region: atl
    :logo: arthur-murray-logo.gif
  vabeach:
    :name: Virginia Beach
    :region: iad
    :logo: arthur-murray-logo.gif
